### ISSUE TITLE
Repeat Result

### ISSUE THREAD

**Issue by PigUnderRoof** [wenhao-gao/mol_opt#16]
Hi @wenhao-gao ,

I am trying to repleat result of Figure 3 in DST paper. Not sure whether I am understanding this right: is mol_opt run.py script followed by  denovo.py from dst repo？ like 0.5K in 2K = 1.5K + 0.5K

**Comment by PigUnderRoof** [comment]
Thanks for your reminding. 

What is size of initial training set of 2K point in figure 3? Failed to repeat with 1500 initial data points.

Are population_size and pool_size same in different dst experiments?

**Comment by futianfan** [comment]
it should be 500 initial data points and 1500 online oracle calls instead of 1500 initial data points and 500 online oracle calls. thanks!
