### ISSUE TITLE
new commit

### ISSUE THREAD

**Issue by futianfan** [wenhao-gao/mol_opt#21]
@GuoJeff 
Hi Jeff, thanks again for your contribution. I further test your PR again, and find smiles_ahc works well, but it has bugs with smiles_aug_mem and smiles_bar.

the error is 

ModuleNotFoundError: No module named 'reinvent_models', i assume you write the new module called reinvent_models, right? do you mind share it with us? 

 It would be great if you can take a look again. I will also try to figure it out.

**Comment by GuoJeff** [comment]
@futianfan 
Hi Tianfan, yes, smiles_aug_mem and smiles_bar require an additional package installed with:

`pip install reinvent-models==0.0.15rc1`

I tried to include this information in the `additional package` in the README.

Thank you for the great repository!

**Comment by futianfan** [comment]
hi Jeff, 

thanks for your prompt response. I install the package and try again. it works! thanks so much!
