### ISSUE TITLE
question about smiles_bar and smiles_aug_mem

### ISSUE THREAD

**Issue by futianfan** [wenhao-gao/mol_opt#22]
hi Jeff, 
@GuoJeff 

when I read your PR about smiles_bar and smiles_aug_mem, I did not find the command "import reinvent_model", I am very curious about how you import the module reinvent_model. thanks so much for your time!

**Comment by GuoJeff** [comment]
@futianfan 
Hi Tianfan, 

Sorry I should have clarified in the PR - both smiles_bar (the version provided here, as the original is based on GraphINVENT) and smiles_aug_mem are formulated based on REINVENT [here](https://github.com/MolecularAI/Reinvent). The pre-trained model was trained using this parent repository which uses reinvent_models. reinvent_models is used here to load this pre-trained model in the bar.py and augmented_memory.py files.

**Comment by futianfan** [comment]
I see. thanks so much, Jeff, for your explanation!
