### ISSUE TITLE
Folders for some baselines seem to be missing

### ISSUE THREAD

**Issue by qky18** [wenhao-gao/mol_opt#25]
Hi, thanks for this wonderful work that brings together a bunch of optimization methods.
However, when I tried to experiment with the provided baselines here, I found that a few methods were not included in the codebase but referenced in `main/run.py`, e.g. hero, gegl, boss, chemo and rationale_rl. 
Could you take a look at what's happening here?

**Comment by futianfan** [comment]
thanks for your interest. we did try these methods. but some are too slow to run on our tasks (e.g., boss, chembo), and some rely on property-specific preprocessing (e.g., rationale_rl), so we decided not to include them in the final version.

**Comment by qky18** [comment]
I see, thanks for answering.
